### ISSUE TITLE
Boss Bar

### ISSUE THREAD

**Issue by DavidxRussell** [Geicomo/CyansSimpleRaiding#1]
Hi!

I've been waiting for a plugin like this for my SMP. Would love a boss bar option instead of chat.

Thank you!

**Comment by Geicomo** [comment]
New release will have the default option show the boss bar notification style, as the health goes down the boss bar color will change. There is also a command to switch between the boss bar and chat notification style. Thanks for the suggestion.
![image](https://github.com/user-attachments/assets/2e2a9b75-763e-4917-8711-b2e3f42f9954)

![image](https://github.com/user-attachments/assets/1109621f-7835-475a-91aa-cd206a38cc6f)
